---
abstract: 'Perl Module to generate and test check digits'
author:
  - 'Songmu <y.songmu@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-CheckDigits
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Songmu/Math-CheckDigits.git
version: 0.03
