---
abstract: 'Perl Module to generate and test check digits'
author:
  - 'Songmu <y.songmu@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.0.53, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-CheckDigits
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Math::CheckDigits:
    file: lib/Math/CheckDigits.pm
    version: 0.04
requires:
  perl: 5.006
resources:
  bugtracker: https://github.com/Songmu/Math-CheckDigits/issues
  homepage: https://github.com/Songmu/Math-CheckDigits
  repository: git://github.com/Songmu/Math-CheckDigits.git
version: 0.04
